# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v0.2.0
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
advanced: false
github_repo: hex-movesthemind
github_user: abilliontrillionstars
gradle_deps_type: gradle/libs.versions.toml
gradle_hex_version_key: hexcasting
gradle_mod_version_key: mod_version
main_branch: main
minecraft_version: 1.20.1
minecraft_version_in_mod_version: false
mod_description: Adds a suite of patterns for summoning and controlling player-like
    entities, provided by the Carpet mod.
mod_display_name: Moves the Mind
modid: movesthemind
multiloader: false
pattern_registry_path: main/java/abilliontrillionstars/movesthemind/casting/MovesthemindPatterns.java
